---
- name: Ensure Apache webroot directory exists
  file:
    path: "/var/www/{{ http_host }}"
    state: directory
    owner: "{{ app_user }}"
    mode: '0755'

- name: Clone or update PHP application from Git {{ branch }}
  git:
    repo: "{{ repo_url }}"
    dest: "/var/www/{{ http_host }}"
    version: "{{ branch }}"
    force: yes
    update: yes
  become: true
