services:
  # Database service
  db:
    image: mysql:8.0-debian
    container_name: mysql_db
    # restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # Web server (Apache + PHP)
  web:
    build: .
    container_name: apache_php
    # restart: unless-stopped
    ports:
      - "8080:80"   # Map port 80 in the container to 8080 on the host
    volumes:
      - ./src:/var/www/html  # Mount the local 'src' folder for development convenience
    depends_on:
      - db

# Define named volumes
volumes:
  db_data: