name: Deploy gcp test

on:
  push:
    branches:
      - main

jobs:
  job_id:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'

    - name: Install SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{secrets.GCP_SSH_PRIVATE_KEY}}" > ~/.ssh/google_compute_engine
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa  ${{secrets.GCP_REMOTE_HOST}} >> ~/.ssh/known_hosts
    - name: Deploy to Google Cloud VM
      run: |
        ssh -i ~/.ssh/google_compute_engine kientrantrung96_gmail_com@34.126.80.103 '
          ls -la
        '

    # - id: 'auth'
    #   uses: 'google-github-actions/auth@v2'
    #   with:
    #     workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
    #     service_account: ${{ secrets.SERVICE_ACCOUNT }}
    #     project_id: redex-website-431108

    # - id: 'compute-ssh'
    #   uses: 'google-github-actions/ssh-compute@v1'
    #   with:
    #     instance_name: 'redexwebsiteuat'
    #     zone: 'asia-southeast1-a'
    #     ssh_private_key: '${{ secrets.GCP_SSH_PRIVATE_KEY }}'
    #     command: 'echo Hello world'
