name: Deploy gcp test

on:
  push:
    branches:
      - main

jobs:
  job_id:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    # - uses: 'actions/checkout@v4'

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.GCP_REMOTE_HOST }}
        username: githubci
        password: ${{ secrets.GCP_PASSWORD }}
        port: 22
        script: whoami
    # - id: 'auth'
    #   uses: 'google-github-actions/auth@v2'
    #   with:
    #     workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
    #     service_account: ${{ secrets.SERVICE_ACCOUNT }}
    #     project_id: redex-website-431108

    # - id: 'compute-ssh'
    #   uses: 'google-github-actions/ssh-compute@v1'
    #   with:
    #     instance_name: 'redexwebsiteuat'
    #     zone: 'asia-southeast1-a'
    #     ssh_private_key: '${{ secrets.GCP_SSH_PRIVATE_KEY }}'
    #     command: 'echo Hello world'
