name: Hotfix
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Release branch'
        required: true

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          # github-api-url: https://git.com/api/v3
          # github-graphql-url: https://git.com/api
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          bump-minor-pre-major: true
          target-branch: ${{ inputs.branch }}