name: release-please

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Release branch'
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Run Release Please
        uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.TOKEN }}
          release-type: simple
          bump-minor-pre-major: true
          target-branch: ${{ inputs.branch }}