name: Deploy preprod

on:
  push:
    branches:
      - main
  # release:
  #   types: [prereleased]

jobs:
  deploy:
    # environment: preprod
    name: Deploy to Remote Server for Prerelease
    runs-on: ubuntu-latest

    steps:
      - uses: 'actions/checkout@v4'

      - name: Set up SSH key
        run: |
          # Create .ssh folder
          mkdir -p ~/.ssh
          echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" > ~/.ssh/google_compute_engine
          chmod 600 ~/.ssh/google_compute_engine

      - name: Get Release Tag
        # This step extracts the release tag (e.g. v1.2.3-rc) from the GitHub event payload
        id: get_tag
        run: |
          # GITHUB_REF may look like refs/tags/v1.2.3
          TAG_NAME="${GITHUB_REF##*/}"
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: "Install Ansible"
        uses: alex-oleshkevich/setup-ansible@master 
        with:
          version: "11.1.0"

      - name: Deploy playbook
        env:
          ANSIBLE_USER: ${{ secrets.ANSIBLE_USER }}
          ANSIBLE_PASS: ${{ secrets.ANSIBLE_PASS }}
        run: |
          export BRANCH=${{ steps.get_tag.outputs.tag_name }}
          cd ansible-playbooks
          ansible-playbook playbook.yml -i inventory.ini --private-key ~/.ssh/google_compute_engine --limit staging --tag=deploy --extra-vars "ansible_user=$ANSIBLE_USER ansible_sudo_pass=$ANSIBLE_PASS ansible_ssh_pass=$ANSIBLE_PASS"

      # - name: SSH to Remote VM and Deploy
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.REMOTE_HOST }}             # e.g. '123.45.67.89'
      #     username: ${{ secrets.REMOTE_USER }}         # e.g. 'ubuntu'
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}           # Your private key stored in GitHub Secrets
      #     port: 22                                     # Adjust if needed
      #     script: |
      #       echo "Deploying prerelease: ${{ steps.get_tag.outputs.tag_name }}"
            