name: Deploy production

on:
  release:
    types: [released]

jobs:
  deploy:
    # environment: preprod
    name: Deploy to Remote Server for Prerelease
    runs-on: ubuntu-latest

    steps:
      - uses: 'actions/checkout@v4'

      - name: Get Release Tag
        # This step extracts the release tag (e.g. v1.2.3-rc) from the GitHub event payload
        id: get_tag
        run: |
          # GITHUB_REF may look like refs/tags/v1.2.3
          TAG_NAME="${GITHUB_REF##*/}"
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: "Install Ansible"
        uses: alex-oleshkevich/setup-ansible@master 
        with:
          version: "11.1.0"

      - name: Deploy playbook
        env:
          ANSIBLE_USER: ${{ secrets.ANSIBLE_USER }}
          ANSIBLE_PASS: ${{ secrets.ANSIBLE_PASS }}
        run: |
          export BRANCH=${{ steps.get_tag.outputs.tag_name }}
          cd ansible-playbooks
          ansible-playbook playbook.yml -i inventory.ini --limit staging --tag=deploy --extra-vars "ansible_user=$ANSIBLE_USER ansible_sudo_pass=$ANSIBLE_PASS ansible_ssh_pass=$ANSIBLE_PASS"

            