---
- hosts: all
  become: true
  gather_facts: false

  roles:
    - role: apache
      tags: apache
    - role: php
      tags: php
    - role: mysql
      tags: mysql
    - role: mysqlbackup
      tags: mysqlbackup
    - role: deployredexweb
      tags: deploy
