##################################################
# DO Community Playbooks: LAMP on Ubuntu 22.04
##################################################
---
- hosts: all
  become: true
  gather_facts: false
  # vars_files:
  #   - vars/default.yml

  roles:
    - role: apache
      tags: apache
    - role: php
      tags: php
    - role: mysql
      tags: mysql
    - role: mysqlbackup
      tags: mysqlbackup
    - role: deployredexweb
      tags: deploy
